### ISSUE TITLE
Options for redirect

### ISSUE THREAD

**Issue by robinglen** [mjgreen145/localise-url#1]
Hello Matthew,

Could you please give us the option so we could have a different status code per redirect?
Use case, maybe some redirects are permanent 301, other temporary 302?

Thanks,
Robin

**Comment by mjgreen145** [comment]
Hi Robin, 

This is a great idea for a feature. Please see version 1.2.0 of the module, where I have included this:
https://www.npmjs.com/package/localise-url

Hopefully that helps.

Thanks, 

Matthew
